### ISSUE TITLE
v2rayx客户端无法启动

### ISSUE THREAD

**Issue by Tony1009** [W-MS/V2RayX-macOS#2]
各位老师好，我是新手，Mac系统，之前用v2rayx一直稳定，前天更新添加订阅信息 ，订阅信息来自cloudss网站，更新后软件自动退出，无法再次启动，点击客户端图标出现是否接入网络字样 然后一闪就没有了，电脑重启，软件卸载重新下载新版本还是这样，请老师帮忙解决，谢谢！

**Comment by W-MS** [comment]
已解决

**Comment by xiatg** [comment]
我也遇到了同样的问题，可以请问一下是怎么解决的吗？

**Comment by xiatg** [comment]
我也遇到了类似的问题，不同之处在于是点击客户端图标没有任何反应。可以请问一下是怎么解决的吗？
